const mongoose = require('mongoose')

const Joi = require('joi')

const exceptionSchema = new mongoose.Schema({
  providerID: { type: String, required: true },
  provider: { type: String, required: true },
  startDate: { type: String, required: true },
  endDate: { type: String, required: true },
  firstDayOfMonth: { type: String, required: false },
  secondDayOfMonth: { type: String, required: false },
  thirdDayOfMonth: { type: String, required: false },
  fourthDayOfMonth: { type: String, required: false },
  fifthDayOfMonth: { type: String, required: false },
  sixthDayOfMonth: { type: String, required: false },
  seventhDayOfMonth: { type: String, required: false },
  eighthDayOfMonth: { type: String, required: false },
  ninthDayOfMonth: { type: String, required: false },
  tenthDayOfMonth: { type: String, required: false },
  eleventhDayOfMonth: { type: String, required: false },
  twelfthDayOfMonth: { type: String, required: false },
  thirteenthDayOfMonth: { type: String, required: false },
  fourteenthDayOfMonth: { type: String, required: false },
  fifteenthDayOfMonth: { type: String, required: false },
  sixteenthDayOfMonth: { type: String, required: false },
  seventeenthDayOfMonth: { type: String, required: false },
  eighteenthDayOfMonth: { type: String, required: false },
  nineteenthDayOfMonth: { type: String, required: false },
  twentiethDayOfMonth: { type: String, required: false },
  twentyFirstDayOfMonth: { type: String, required: false },
  twentySecondDayOfMonth: { type: String, required: false },
  twentyThirdDayOfMonth: { type: String, required: false },
  twentyFourthDayOfMonth: { type: String, required: false },
  twentyFifthDayOfMonth: { type: String, required: false },
  twentySixthDayOfMonth: { type: String, required: false },
  twentySeventhDayOfMonth: { type: String, required: false },
  twentyEighthDayOfMonth: { type: String, required: false },
  twentyNinthDayOfMonth: { type: String, required: false },
  thirtiethDayOfMonth: { type: String, required: false },
  thirtyFirstDayOfMonth: { type: String, required: false },

  amStartTime: { type: String, required: true },
  amEndTime: { type: String, required: true },
  pmStartTime: { type: String, required: true },
  pmEndTime: { type: String, required: true },
  exceptionMon: { type: String, required: true },
  exceptionTues: { type: String, required: true },
  exceptionWed: { type: String, required: true },
  exceptionThurs: { type: String, required: true },
  exceptionFri: { type: String, required: true },
  addedDate: { type: String, required: true },
  lastUpdated: { type: String, required: false },
})

const Exception = mongoose.model('exception', exceptionSchema)

const validate = (data) => {
  const schema = Joi.object({
    providerID: Joi.number().required().label('Provider ID'),
    provider: Joi.string().required().label('Provider'),
    startDate: Joi.string().required().label('Start Date'),
    endDate: Joi.string().required().label('End Date'),
    firstDayOfMonth: Joi.string().label('First Day of Month'),
    secondDayOfMonth: Joi.string().label('Second Day of Month'),
    thirdDayOfMonth: Joi.string().label('Third Day of Month'),
    fourthDayOfMonth: Joi.string().label('Fourth Day of Month'),
    fifthDayOfMonth: Joi.string().label('Fifth Day of Month'),
    sixthDayOfMonth: Joi.string().label('Sixth Day of Month'),
    seventhDayOfMonth: Joi.string().label('Seventh Day of Month'),
    eighthDayOfMonth: Joi.string().label('Eighth Day of Month'),
    ninthDayOfMonth: Joi.string().label('Ninth Day of Month'),
    tenthDayOfMonth: Joi.string().label('Tenth Day of Month'),
    eleventhDayOfMonth: Joi.string().label('Eleventh Day of Month'),
    twelfthDayOfMonth: Joi.string().label('Twelfth Day of Month'),
    thirteenthDayOfMonth: Joi.string().label('Thirteenth Day of Month'),
    fourteenthDayOfMonth: Joi.string().label('Fourteenth Day of Month'),
    fifteenthDayOfMonth: Joi.string().label('Fifteenth Day of Month'),
    sixteenthDayOfMonth: Joi.string().label('Sixteenth Day of Month'),
    seventeenthDayOfMonth: Joi.string().label('Seventeenth Day of Month'),
    eighteenthDayOfMonth: Joi.string().label('Eighteenth Day of Month'),
    nineteenthDayOfMonth: Joi.string().label('Nineteenth Day of Month'),
    twentiethDayOfMonth: Joi.string().label('Twentieth Day of Month'),
    twentyFirstDayOfMonth: Joi.string().label('Twenty First Day of Month'),
    twentySecondDayOfMonth: Joi.string().label('Twenty Second Day of Month'),
    twentyThirdDayOfMonth: Joi.string().label('Twenty Third Day of Month'),
    twentyFourthDayOfMonth: Joi.string().label('Twenty Fourth Day of Month'),
    twentyFifthDayOfMonth: Joi.string().label('Twenty Fifth Day of Month'),
    twentySixthDayOfMonth: Joi.string().label('Twenty Sixth Day of Month'),
    twentySeventhDayOfMonth: Joi.string().label('Twenty Seventh Day of Month'),
    twentyEighthDayOfMonth: Joi.string().label('Twenty Eighth Day of Month'),
    twentyNinthDayOfMonth: Joi.string().label('Twenty Ninth Day of Month'),
    thirtiethDayOfMonth: Joi.string().label('Thirtieth Day of Month'),
    thirtyFirstDayOfMonth: Joi.string().label('Thirty First Day of Month'),

    amStartTime: Joi.string().required().label('AM Start Time'),
    amEndTime: Joi.string().required().label('AM End Time'),
    pmStartTime: Joi.string().required().label('PM Start Time'),
    pmEndTime: Joi.string().required().label('PM End Time'),
    exceptionMon: Joi.string().required().label('Exception'),
    exceptionTues: Joi.string().required().label('Exception'),
    exceptionWed: Joi.string().required().label('Exception'),
    exceptionThurs: Joi.string().required().label('Exception'),
    exceptionFri: Joi.string().required().label('Exception'),
    addedDate: Joi.string().required().label('Date Created'),
    lastUpdated: Joi.string().label('Last Updated'),

  })
  return schema.validate(data)
}

module.exports = { Exception, validate }
